/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bibliotecaInterfaces;

/**
 *
 * @author IVAN
 */
public class BibliotecaVista extends javax.swing.JFrame {

    /**
     * Creates new form BibliotecaVista
     */
    public BibliotecaVista() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonInicio = new javax.swing.JButton();
        jButtonAutores = new javax.swing.JButton();
        jButtonLibros = new javax.swing.JButton();
        jTabbedPaneMenu = new javax.swing.JTabbedPane();
        jPanelInicio = new javax.swing.JPanel();
        jTextFieldBusquedaPrincipal = new javax.swing.JTextField();
        jButtonBusquedaPrincipal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanelLibros = new javax.swing.JPanel();
        jPanelAutores = new javax.swing.JPanel();
        jRadioButtonBuscarAutor = new javax.swing.JRadioButton();
        jRadioButtonCrearAutor = new javax.swing.JRadioButton();
        jButtonCrearAutor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombreAutor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescripcionAutor = new javax.swing.JTextArea();
        jLabelAccionAutor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldBusquedaAutor = new javax.swing.JTextField();
        jButtonBusquedaAutor = new javax.swing.JButton();
        jButtonEditarAutor = new javax.swing.JButton();
        jButtonEliminarAutor = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonInicio.setText("Inicio");
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });

        jButtonAutores.setText("Gestion autores");
        jButtonAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAutoresActionPerformed(evt);
            }
        });

        jButtonLibros.setText("Gestion libros");
        jButtonLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLibrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAutores)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonLibros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButtonInicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jButtonInicio)
                .addGap(18, 18, 18)
                .addComponent(jButtonAutores)
                .addGap(18, 18, 18)
                .addComponent(jButtonLibros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextFieldBusquedaPrincipal.setText("Inserte el nombre o autor");
        jTextFieldBusquedaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBusquedaPrincipalMouseClicked(evt);
            }
        });
        jTextFieldBusquedaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBusquedaPrincipalActionPerformed(evt);
            }
        });

        jButtonBusquedaPrincipal.setText("Q");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Busqueda");

        javax.swing.GroupLayout jPanelInicioLayout = new javax.swing.GroupLayout(jPanelInicio);
        jPanelInicio.setLayout(jPanelInicioLayout);
        jPanelInicioLayout.setHorizontalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInicioLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jTextFieldBusquedaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonBusquedaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInicioLayout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel1)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanelInicioLayout.setVerticalGroup(
            jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInicioLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBusquedaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBusquedaPrincipal))
                .addContainerGap(455, Short.MAX_VALUE))
        );

        jTabbedPaneMenu.addTab("Inicio", jPanelInicio);

        javax.swing.GroupLayout jPanelLibrosLayout = new javax.swing.GroupLayout(jPanelLibros);
        jPanelLibros.setLayout(jPanelLibrosLayout);
        jPanelLibrosLayout.setHorizontalGroup(
            jPanelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 662, Short.MAX_VALUE)
        );
        jPanelLibrosLayout.setVerticalGroup(
            jPanelLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );

        jTabbedPaneMenu.addTab("Libros", jPanelLibros);

        jRadioButtonBuscarAutor.setText("Buscar");
        jRadioButtonBuscarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonBuscarAutorActionPerformed(evt);
            }
        });

        jRadioButtonCrearAutor.setText("Crear");
        jRadioButtonCrearAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCrearAutorActionPerformed(evt);
            }
        });

        jButtonCrearAutor.setText("Crear");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Descripcion:");

        jTextFieldNombreAutor.setText("Ingrese el nombre del autor");
        jTextFieldNombreAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNombreAutorMouseClicked(evt);
            }
        });

        jTextAreaDescripcionAutor.setColumns(20);
        jTextAreaDescripcionAutor.setRows(5);
        jTextAreaDescripcionAutor.setText("Ingrese la descripcion del autor");
        jTextAreaDescripcionAutor.setMaximumSize(new java.awt.Dimension(232, 125));
        jTextAreaDescripcionAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextAreaDescripcionAutorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextAreaDescripcionAutor);

        jLabelAccionAutor.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelAccionAutor.setText("Crear autor");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Buscar autor");

        jTextFieldBusquedaAutor.setText("Ingrese el nombre del autor");
        jTextFieldBusquedaAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldBusquedaAutorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextFieldBusquedaAutorMouseExited(evt);
            }
        });
        jTextFieldBusquedaAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBusquedaAutorActionPerformed(evt);
            }
        });

        jButtonBusquedaAutor.setText("Q");

        jButtonEditarAutor.setText("Editar");
        jButtonEditarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarAutorActionPerformed(evt);
            }
        });

        jButtonEliminarAutor.setText("Eliminar");

        javax.swing.GroupLayout jPanelAutoresLayout = new javax.swing.GroupLayout(jPanelAutores);
        jPanelAutores.setLayout(jPanelAutoresLayout);
        jPanelAutoresLayout.setHorizontalGroup(
            jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAutoresLayout.createSequentialGroup()
                .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAutoresLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabelAccionAutor))
                    .addGroup(jPanelAutoresLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jButtonCrearAutor))
                    .addGroup(jPanelAutoresLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel5))
                    .addGroup(jPanelAutoresLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombreAutor)
                            .addComponent(jScrollPane1)
                            .addComponent(jTextFieldBusquedaAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBusquedaAutor)
                        .addGap(63, 63, 63)
                        .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonBuscarAutor)
                            .addComponent(jRadioButtonCrearAutor)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAutoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEliminarAutor)
                            .addComponent(jButtonEditarAutor))
                        .addGap(7, 7, 7)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanelAutoresLayout.setVerticalGroup(
            jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAutoresLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldBusquedaAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonBusquedaAutor))
                    .addGroup(jPanelAutoresLayout.createSequentialGroup()
                        .addComponent(jRadioButtonBuscarAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonCrearAutor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jButtonEditarAutor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonEliminarAutor)
                .addGap(30, 30, 30)
                .addComponent(jLabelAccionAutor)
                .addGap(36, 36, 36)
                .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNombreAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelAutoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButtonCrearAutor)
                .addGap(23, 23, 23))
        );

        jTabbedPaneMenu.addTab("Autores", jPanelAutores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPaneMenu)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPaneMenu)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 255, 255));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        // TODO add your handling code here:
        this.jTabbedPaneMenu.setSelectedComponent(this.jPanelInicio);
    }//GEN-LAST:event_jButtonInicioActionPerformed

    private void jButtonAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAutoresActionPerformed
        // TODO add your handling code here:
        this.jTabbedPaneMenu.setSelectedComponent(this.jPanelAutores);
        this.buttonGroup1.add(this.jRadioButtonBuscarAutor);
        this.buttonGroup1.add(this.jRadioButtonCrearAutor);
    }//GEN-LAST:event_jButtonAutoresActionPerformed

    private void jButtonLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLibrosActionPerformed
        // TODO add your handling code here:
        this.jTabbedPaneMenu.setSelectedComponent(this.jPanelLibros);
    }//GEN-LAST:event_jButtonLibrosActionPerformed

    private void jRadioButtonBuscarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonBuscarAutorActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButtonBuscarAutorActionPerformed

    private void jRadioButtonCrearAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCrearAutorActionPerformed
        // TODO add your handling code here:
        this.jLabelAccionAutor.setText("Crear autor");
    }//GEN-LAST:event_jRadioButtonCrearAutorActionPerformed

    private void jTextFieldBusquedaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaPrincipalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextFieldBusquedaPrincipalActionPerformed

    private void jTextFieldBusquedaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaPrincipalMouseClicked
        // TODO add your handling code here:
        this.jTextFieldBusquedaPrincipal.setText(null);
    }//GEN-LAST:event_jTextFieldBusquedaPrincipalMouseClicked

    private void jTextFieldNombreAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNombreAutorMouseClicked
        // TODO add your handling code here:
        this.jTextFieldNombreAutor.setText(null);
    }//GEN-LAST:event_jTextFieldNombreAutorMouseClicked

    private void jTextAreaDescripcionAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextAreaDescripcionAutorMouseClicked
        // TODO add your handling code here:
        this.jTextAreaDescripcionAutor.setText(null);
    }//GEN-LAST:event_jTextAreaDescripcionAutorMouseClicked

    private void jTextFieldBusquedaAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaAutorMouseClicked
        // TODO add your handling code here:
        this.jTextFieldBusquedaAutor.setText(null);
        
    }//GEN-LAST:event_jTextFieldBusquedaAutorMouseClicked

    private void jButtonEditarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarAutorActionPerformed
        // TODO add your handling code here:
        this.jLabelAccionAutor.setText("Editar autor");
    }//GEN-LAST:event_jButtonEditarAutorActionPerformed

    private void jTextFieldBusquedaAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBusquedaAutorActionPerformed

    private void jTextFieldBusquedaAutorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldBusquedaAutorMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBusquedaAutorMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BibliotecaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BibliotecaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BibliotecaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BibliotecaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BibliotecaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAutores;
    private javax.swing.JButton jButtonBusquedaAutor;
    private javax.swing.JButton jButtonBusquedaPrincipal;
    private javax.swing.JButton jButtonCrearAutor;
    private javax.swing.JButton jButtonEditarAutor;
    private javax.swing.JButton jButtonEliminarAutor;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonLibros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAccionAutor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAutores;
    private javax.swing.JPanel jPanelInicio;
    private javax.swing.JPanel jPanelLibros;
    private javax.swing.JRadioButton jRadioButtonBuscarAutor;
    private javax.swing.JRadioButton jRadioButtonCrearAutor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneMenu;
    private javax.swing.JTextArea jTextAreaDescripcionAutor;
    private javax.swing.JTextField jTextFieldBusquedaAutor;
    private javax.swing.JTextField jTextFieldBusquedaPrincipal;
    private javax.swing.JTextField jTextFieldNombreAutor;
    // End of variables declaration//GEN-END:variables
}
